# Generated by Django 4.2.6 on 2023-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='Department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='team_lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
