# Generated by Django 4.2.6 on 2024-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novusapp', '0003_alter_analyst_is_active_alter_company_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
