# Generated by Django 4.2.6 on 2023-12-05 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novusapp', '0003_analyst_is_active_company_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analyst',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
