# Generated by Django 4.2.6 on 2023-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novusapp', '0004_analyst_created_at_analyst_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
